/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package demo;

import org.apache.commons.math3.primes.Primes;

import java.util.Arrays;

public class Library {
    public static void main(String[] args) {

        System.out.println(
                String.format("O numero é primo? %s",
                        Primes.isPrime(args.length > 0 ? Integer.valueOf(args[0]) : 0))
        );
    }
    public boolean someLibraryMethod() {
        return true;
    }
}
